app/models/User.py
from app.extensions import db


class User(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    username = db.Column(db.String)
    password = db.Column(db.String)

    # return a printable representation of the object
    def __repr__(self):
        return "<UserID {}>".format(self.id)

app/forms/auth_forms.py
# Desc: Forms for authentication
from flask_wtf import FlaskForm
from wtforms import StringField, PasswordField, SubmitField
from wtforms.validators import InputRequired, Email, Length, EqualTo


class LoginForm(FlaskForm):
    """Login Form validation"""

    email = StringField("Email", validators=[InputRequired(), Email()])
    password = PasswordField("Password", validators=[InputRequired(), Length(min=6)])
    submit = SubmitField("LOGIN")


class SignupForm(FlaskForm):
    """Signup Form validation"""

    email = StringField("Email", validators=[InputRequired(), Email()])
    password = PasswordField("Password", validators=[InputRequired(), Length(min=6)])
    password_confirm = PasswordField(
        "Confirm Password",
        validators=[InputRequired(), Length(min=6), EqualTo("password")],
    )
    submit = SubmitField("SIGNUP")

app/__init__.py
from flask import Flask
from flask_wtf import CSRFProtect

from app import routes
from app.extensions import db, csrf
from config.config import config

from log import Log


def create_app(config_name="default"):
    app = Flask(__name__, template_folder="templates", static_folder="static")
    app.config.from_object(config[config_name])
    config[config_name].init_app(app)

    # register blueprints
    routes.init_app(app)

    # initialize extensions here
    # initialize sqlalchemy
    db.init_app(app)
    # initialize csrf
    csrf.init_app(app)

    # initialize log
    Log.init_app(app)

    # log info when app is created
    Log.logger().info(f"Creating app with config: {config_name}")

    # test route
    @app.route("/test")
    def test():
        return "<h1>Testing the Flask Application Factory Pattern</h1>"

    return app

app/routes/__init__.py
from flask import Flask

from app.routes.auth import auth_bp
from routes.home import home_bp


def init_app(app: Flask) -> None:
    """
    Register blueprints, new files added to routes folder should be registered here
    :param app: Flask app
    :return: None
    """
    app.register_blueprint(auth_bp)
    app.register_blueprint(home_bp)

app/routes/auth.py
import json
import os

import firebase_admin
import pyrebase
from firebase_admin import credentials, auth as firebase_auth
from flask import Blueprint, redirect, url_for, session, render_template, request

from app.utils.decorators.auth_decorator import login_required
from forms.auth_forms import LoginForm, SignupForm
from log import Log

auth_bp = Blueprint("auth", __name__, url_prefix="/auth")
basedir = os.path.abspath(os.path.dirname(__file__))
firebase_config_path = os.path.normpath(os.path.join(basedir, "../config/firebase"))

# Connect to firebase
cred = credentials.Certificate(
    os.path.join(firebase_config_path, "firebaseAdminConfig.json")
)
firebase = firebase_admin.initialize_app(cred)
# pyrebase4 which is a python wrapper for firebase
pb = pyrebase.initialize_app(
    json.load(open(os.path.join(firebase_config_path, "firebaseConfig.json")))
)


# auth routes, user click login button, redirect to login page
@auth_bp.route("/")
def auth():
    form = LoginForm()
    return render_template("login.html", form=form)


@auth_bp.route("/redirect_to_signup")
def redirect_to_signup():
    """Redirect to signup page"""
    form = SignupForm()
    return render_template("signup.html", form=form)


@auth_bp.route("/signup", methods=["POST", "GET"])
def signup():
    form = SignupForm()
    if form.validate_on_submit():
        email = request.form.get("email")
        password = request.form.get("password")
        try:
            user = firebase_auth.create_user(email=email, password=password)
            uid = user.uid
            Log.logger().info(f"User {uid} signed up")
            return redirect(
                url_for(
                    "auth.login",
                    _scheme=os.environ.get("REDIRECT_PROTOCOL"),
                    _external=True,
                )
            )
        except Exception as e:
            Log.logger().error(f"Error when signing up: {e}")
            message = "Error when signing up, the provided email already exists in the system, please try again"
            return render_template("login.html", message=message, form=form)
    return render_template("signup.html", form=form)


@auth_bp.route("/login", methods=["POST", "GET"])
def login():
    form = LoginForm()

    if form.validate_on_submit():
        email = request.form.get("email")
        password = request.form.get("password")
        try:
            user = pb.auth().sign_in_with_email_and_password(email, password)
            uid = user["localId"]
            Log.logger().info(f"User {uid} logged in")
            session["user_id"] = uid
            return redirect(
                url_for(
                    "home.home_page",
                    _scheme=os.environ.get("REDIRECT_PROTOCOL"),
                    _external=True,
                )
            )
        except Exception as e:
            Log.logger().error(f"Error when logging in: {e}")
            message = "Error when logging in, please try again or sign up first"
            return render_template("login.html", message=message, form=form)
    return render_template("login.html", form=form)


@auth_bp.route("/logout")
@login_required
def logout():
    """
    User logout
    clear session
    :return: redirect to index
    """
    user_id = session.get("user_id")
    session.clear()
    Log.logger().info(f"User {user_id} logged out")
    return redirect(
        url_for(
            "home.home_page",
            _scheme=os.environ.get("REDIRECT_PROTOCOL"),
            _external=True,
        )
    )

app/routes/home.py
from flask import Blueprint, render_template, session

from log import Log

home_bp = Blueprint("home", __name__)


# home page route
@home_bp.route("/")
def home_page():
    """View function for Home Page."""
    uid = session.get("user_id")
    if uid == "" or uid is None:
        Log.logger().info("Home page accessed without login")
    else:
        Log.logger().info(f"Home page accessed by user {uid}")
    return render_template("index.html")

app/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link rel="shortcut icon"
          href="{{ url_for('static', filename='favicon.ico') }}"
          type="image/x-icon"
    >
    <link rel="icon"
          href="{{ url_for('static', filename='favicon.ico') }}"
          type="image/x-icon"
    >
    <link href="https://cdn.jsdelivr.net/npm/daisyui@2.51.5/dist/full.css"
          rel="stylesheet"
          type="text/css"
    />
    <script src="https://cdn.tailwindcss.com"></script>
    <title>{% block title %} {% endblock %}</title>
</head>
<body>
    {# two different navi determined by if user has logined in #}
    {% if "user_id" in session %}
        {#    navi for logined user    #}
        <div class="navbar bg-base-300">
            <div class="flex-1">
                <a class="btn btn-ghost normal-case text-xl">Flask-Scaffolding</a>
            </div>
            <div class="flex-none">
                <div class="dropdown dropdown-end">
                    <label tabindex="0"
                           class="btn btn-ghost btn-circle avatar"
                    >
                        <div class="w-10 rounded-full">
                            <img src="{{ url_for('static', filename='default_avatar.png') }}"/>
                        </div>
                    </label>
                    <ul tabindex="0"
                        class="mt-3 p-2 shadow menu menu-compact dropdown-content bg-base-100 rounded-box w-52"
                    >
                        <li>
                            <a>Profile</a>
                        </li>
                        <li>
                            <a>Settings</a>
                        </li>
                        <li>
                            <a href="{{ url_for('auth.logout') }}">Logout</a>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
    {% else %}
        {#    navi for guest user    #}
        <div class="navbar bg-base-300">
            <div class="flex-1">
                <a class="btn btn-ghost normal-case text-xl">Flask-Scaffolding</a>
            </div>
            <div class="navbar-end">
                <a class="btn"
                   onclick="window.location.href='{{ url_for('auth.auth') }}'"
                >Login / Signup</a>
            </div>
        </div>
    {% endif %}

    {#    main content    #}
    <div class="container mx-auto">
        {% block content %}

        {% endblock %}
    </div>

    {#    footer    #}
    <footer class="footer footer-center p-4 bg-base-300 text-base-content">
        <div>
            <p>Copyright © 2023 - All right reserved by Alex-Wang Industries Ltd</p>
        </div>
    </footer>
</body>
</html>

app/templates/index.html
{% extends "base.html" %}

{% block title %}Home{% endblock %}

{% block content %}
    <div class="hero min-h-screen"
         style="background-image: url('../static/background.jpeg');"
    >
        <div class="hero-overlay bg-opacity-60"></div>
        <div class="hero-content text-center text-neutral-content">
            <div class="max-w-md">
                <h1 class="mb-5 text-5xl font-bold">Hello there</h1>
                <p class="mb-5">Provident cupiditate voluptatem et in. Quaerat fugiat ut assumenda excepturi
                    exercitationem quasi. In deleniti eaque aut repudiandae et a id nisi.</p>
                <button class="btn btn-primary">Get Started</button>
            </div>
        </div>
    </div>
{% endblock %}

app/templates/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link href="https://cdn.jsdelivr.net/npm/daisyui@2.51.5/dist/full.css"
          rel="stylesheet"
          type="text/css"
    />
    <script src="https://cdn.tailwindcss.com"></script>
    <link rel="shortcut icon"
          href="{{ url_for('static', filename='favicon.ico') }}"
          type="image/x-icon"
    >
    <link rel="icon"
          href="{{ url_for('static', filename='favicon.ico') }}"
          type="image/x-icon"
    >
    <title>Login</title>
</head>
<body>
    {% if message %}
        <div class="alert alert-error shadow-lg">
            <div>
                <svg xmlns="http://www.w3.org/2000/svg"
                     class="stroke-current flex-shrink-0 h-6 w-6"
                     fill="none"
                     viewBox="0 0 24 24"
                >
                    <path stroke-linecap="round"
                          stroke-linejoin="round"
                          stroke-width="2"
                          d="M10 14l2-2m0 0l2-2m-2 2l-2-2m2 2l2 2m7-2a9 9 0 11-18 0 9 9 0 0118 0z"
                    />
                </svg>
                <span>{{ message }}</span>
            </div>
        </div>
    {% endif %}
    <div class="hero min-h-screen bg-base-200">
        <div class="hero-content flex-col lg:flex-row-reverse">
            <div class="text-center lg:text-left">
                <h1 class="text-5xl font-bold">Login now!</h1>
                <p class="py-6">Provident cupiditate voluptatem et in. Quaerat fugiat ut assumenda excepturi
                    exercitationem quasi. In deleniti eaque aut repudiandae et a id nisi.</p>
            </div>
            <div class="card flex-shrink-0 w-full max-w-sm shadow-2xl bg-base-100">
                {% if form %}
                    <form action="{{ url_for('auth.login') }}"
                          method="post"
                    >
                        {{ form.csrf_token }}
                        <div class="card-body">
                            <div class="form-control">
                                <label class="label">
                                    <span class="label-text">Email</span>
                                </label>
                                {{ form.email(class_="input input-bordered") }}
                            </div>
                            <div class="form-control">
                                <label class="label">
                                    <span class="label-text">Password</span>
                                </label>
                                {{ form.password(class_="input input-bordered") }}
                                <label class="label">
                                    <a href="#"
                                       class="label-text-alt link link-hover"
                                    >Forgot Password?</a>
                                </label>
                            </div>
                            <div class="columns-2">
                                <div class="ml-6">
                                    <label class="label">
                                        <span class="label-text">Have Account?</span>
                                    </label>
                                    <div class="form-control">
                                        {{ form.submit(class_="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded-full w-24 h-12") }}
                                    </div>
                                </div>

                                <div class="ml-6">
                                    <label class="label">
                                        <span class="label-text">New Here?</span>
                                    </label>
                                    <div class="form-control">
                                        <button class="bg-orange-500 hover:bg-orange-700 text-white font-bold py-2 px-4 rounded-full w-24 h-12bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded-full w-24 h-12"
                                                id="register"
                                                onclick="window.location.href='{{ url_for('auth.redirect_to_signup') }}'"
                                        >SIGNUP
                                        </button>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </form>
                {% endif %}
            </div>
        </div>
    </div>
</body>
</html>

app/templates/signup.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link href="https://cdn.jsdelivr.net/npm/daisyui@2.51.5/dist/full.css"
          rel="stylesheet"
          type="text/css"
    />
    <script src="https://cdn.tailwindcss.com"></script>
    <link rel="shortcut icon"
          href="{{ url_for('static', filename='favicon.ico') }}"
          type="image/x-icon"
    >
    <link rel="icon"
          href="{{ url_for('static', filename='favicon.ico') }}"
          type="image/x-icon"
    >
    <title>SignUp</title>
</head>
<body>
    {% if message %}
        <div class="alert alert-error shadow-lg">
            <div>
                <svg xmlns="http://www.w3.org/2000/svg"
                     class="stroke-current flex-shrink-0 h-6 w-6"
                     fill="none"
                     viewBox="0 0 24 24"
                >
                    <path stroke-linecap="round"
                          stroke-linejoin="round"
                          stroke-width="2"
                          d="M10 14l2-2m0 0l2-2m-2 2l-2-2m2 2l2 2m7-2a9 9 0 11-18 0 9 9 0 0118 0z"
                    />
                </svg>
                <span>{{ message }}</span>
            </div>
        </div>
    {% endif %}
    <div class="hero min-h-screen bg-base-200">
        <div class="hero-content flex-col lg:flex-row-reverse">
            <div class="text-center lg:text-left">
                <h1 class="text-5xl font-bold">Sign Up now!</h1>
                <p class="py-6">Provident cupiditate voluptatem et in. Quaerat fugiat ut assumenda excepturi
                    exercitationem quasi. In deleniti eaque aut repudiandae et a id nisi.</p>
            </div>
            <div class="card flex-shrink-0 w-full max-w-sm shadow-2xl bg-base-100">
                {% if form %}
                    <form action="{{ url_for('auth.signup') }}"
                          method="post"
                    >
                        {{ form.csrf_token }}
                        <div class="card-body">
                            <div class="form-control">
                                <label class="label">
                                    <span class="label-text">Email</span>
                                </label>
                                {{ form.email(class_="input input-bordered") }}
                            </div>
                            <div class="form-control">
                                <label class="label">
                                    <span class="label-text">Password</span>
                                </label>
                                {{ form.password(class_="input input-bordered") }}
                            </div>
                            <div class="form-control">
                                <label class="label">
                                    <span class="label-text">Confirm Password</span>
                                </label>
                                {{ form.password_confirm(class_="input input-bordered") }}
                            </div>

                            <div class="ml-6">
                                <div class="form-control">
                                    {{ form.submit(class_="bg-orange-500 hover:bg-orange-700 text-white font-bold py-2 px-4 rounded-full h-12bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded-full h-12 mt-6 mr-6") }}
                                </div>
                            </div>
                        </div>
                    </form>
                {% endif %}
            </div>
        </div>
    </div>
</body>
</html>